Feature server authentication
dav793/proyecto-todo-server pull request #2
Opened 2019-04-08 21:13 UTC by andresnboza

Este pull requestya tiene el git ignore bien tanto en el config/enviroment.js, evitando client y dist

2019-04-12 23:45 UTC, dav793 requested changes
Revisado! Muchas gracias por el brete mae!

Porfa hágale los cambios que puse y quedamos listos! Cualquier cosa si necesita clarificar algo me avisa.

Y por ahora no tiene que hacer el cambio del package.json ni lo de separar el branch en sus features.

2019-04-12 23:45 UTC, dav793 commented on package.json
>      "serve": "tsc && export NODE_ENV=production && nodemon dist/index.js"
Es bueno que los package.json siempre tengan definido el script "start" por convención, ya que la mayoría de gente va a intentar correr npm install y npm start de una vez. Si no tiene start, es bueno entonces que documente en el README.md cómo correr el programa, o mejor aún qué hace cada script. 

No es necesario que lo haga esta vez, pero para que lo tenga en cuenta como una ayuda a sus compañeros y a ud mismo más adelante, en especial conforme se van haciendo muchos los proyectos o muchas las tecnologías. El readme es un buen lugar para documentar esas cosas porque existe en proyectos de prácticamente cualquier tecnología.

2019-04-12 23:45 UTC, dav793 commented on src/app.ts
> +        console.log('despues de autenticacion ')
Evitemos introducir mensajes de consola no necesarios en master

2019-04-12 23:45 UTC, dav793 commented on src/controllers/todo.controller.ts
> +const Todo = require('../models/todo.model');
Recuerde compartimentalizar los PRs, trabaje en un feature a la vez. Si este branch es de user authentication, no debería ir cosas del todo controller aquí, ni del CRUD de users.

2019-04-12 23:45 UTC, dav793 commented on src/controllers/user.controller.ts
>              firstName: req.body.firstName,
En general, evite setear explícitamente miembro por miembro los bodies de requests, a menos que sea necesario. 

En createUser es necesario por la forma en que lo hizo (creando una instancia de un nuevo User), pero en el caso de updateUser no hay motivo para especificar las propiedades una por una. Hace el código más frágil porque si cambiara el modelo de User, va a haber que recordar venir y cambiarlo aquí también o de lo contrario se introduce un bug. Además, tampoco está documentado como para que uno sepa que tiene que cambiar las funciones updateUser y createUser cuando/si se cambia el user model. Si otra persona tuviera que cambiar el user model, o usted mismo tuviera que cambiarlo en unos meses, probablemente no se acuerde y le aparezca un bug que podríamos evitar desde ya.

Entonces, lo que puede hacer es algo como `User.findByIdAndUpdate(id, { $set: req.body } ...` y dejar que la validación de Mongoose se encarge de detectar malos inputs. 

Pero también recuerde que antes de hacer eso tiene que asegurarse de remover las propiedades que no quiere que sean modificables por la función (hash y salt) y que podrían o no venir definidos en el body del request. De lo contrario estaría dejando un exploit que podría potencialmente permitir a usuarios cambiar el password de otros usuarios. Eso sería así:
```
delete req.body.hash;
delete req.body.salt;
```

2019-04-12 23:45 UTC, dav793 commented on src/routes/index.router.ts
> +                "updatePassword: true,
Aquí en la documentación de la línea 50 te faltó incluir el password como un requisito del body del request. Si intenta hacer un request con solo estas propiedades tira error.

2019-04-12 23:45 UTC, dav793 commented on src/routes/user.router.ts
> +        this.router.get('/user/:username', userController.getUserByUsername);
Aquí el segmento de ruta 'user' no nos ayuda a saber qué produce. Cámbielo por algo más descriptivo, por ejemplo 'byUsername'.

2019-04-12 23:45 UTC, dav793 commented on src/controllers/user.controller.ts
>              firstName: req.body.firstName,
Otra problema de especificar las propiedades una por una, es que si quisiéramos solo cambiar unas cuantas propiedades pero no todas, de forma que el body del request fuera por ejemplo:
```
{
    "firstName": "Pedro"
}
```
se cambiaría el nombre a Pedro, pero todas las demás propiedades quedarían null o undefined en el documento de la BD. Si le damos a `findByIdAndUpdate` el `req.body` directamente ya no tenemos esa limitación, se cambia solo lo que venga definido en el cuerpo del request.

2019-04-14 00:38 UTC, andresnboza commented on package.json
>      "serve": "tsc && export NODE_ENV=production && nodemon dist/index.js"
listo el cambio, para que de una vez me vaya acostumbrando

2019-04-14 00:38 UTC, andresnboza commented on src/app.ts
> +        console.log('despues de autenticacion ')
listo, se me fue ese console log

2019-04-14 00:55 UTC, andresnboza commented on src/routes/user.router.ts
> +        this.router.get('/user/:username', userController.getUserByUsername);
listo

2019-04-14 00:55 UTC, andresnboza commented on src/routes/index.router.ts
> +                "updatePassword: true,
listo

2019-04-14 00:58 UTC, andresnboza commented on src/controllers/user.controller.ts
>              firstName: req.body.firstName,
listo

2019-04-14 00:58 UTC, andresnboza commented on src/controllers/todo.controller.ts
> +const Todo = require('../models/todo.model');
si esque me emociono, pero voy a tratar de hacer mas PR

2019-04-15 20:30 UTC, dav793 requested changes

2019-04-15 20:30 UTC, dav793 commented on ReadMe.txt
>  Creator: Andres Navarrete Boza
Excelente! Una cosa más con esto solo para que sepa, en proyectos hosteados en github el readme casi siempre se llama README.md por convención.

El formato md (Markdown) permite utilizar elementos de estilo en documentos que github puede mostrar, como: 
* headers 
* listas
* `fragmentos de código` 
* [links](https://www.youtube.com/watch?v=dQw4w9WgXcQ)
* emojis 
* etc. 

Eso aplica no solo para el README sino para cualquier documento .md y para cualquier parte donde uno pueda escribir texto en github, como por ejemplo **estos comentarios**. Le recomiendo que lo use! :metal:

Por si quiere ver más sobre markdown, le dejo [este link](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet).

Y este es la [lista de emojis](https://gist.github.com/rxaviers/7360908)

2019-04-15 20:30 UTC, dav793 commented on src/routes/user.router.ts
> +        this.router.get('/user/:byUsername', userController.getUserByUsername);
Al revés, osea `/byUsername/:username`.

La última parte es solo el nombre de la variable, eso no se ve en el URL de la ruta. La primera parte es la que saldría así mismo en el URL de la ruta. Eso es lo que nos interesa cambiar para seguir buenas prácticas de diseño de REST APIs.

Ejemplo de un URL que aplicaría a la ruta que queremos: 
```
.../byUsername/david123
```

2019-04-15 20:39 UTC, dav793 commented
Porfa también vea este issue: https://github.com/dav793/proyecto-todo-server/issues/3

2019-04-15 21:55 UTC, dav793 commented on src/controllers/user.controller.ts
> +        await User.findByIdAndUpdate(id, { $set: req.body }, { new: true });
Recuerde que antes de esta línea tiene que remover las propiedades que no quiere que sean modificables aquí (hash y salt) ya que podrían o no venir definidos en el body del request. De lo contrario estaría dejando un exploit que podría potencialmente permitir a usuarios cambiar el password de otros usuarios. Eso sería así:
```
delete req.body.hash;
delete req.body.salt;
```

2019-04-17 22:26 UTC, andresnboza commented on src/controllers/user.controller.ts
> +        await User.findByIdAndUpdate(id, { $set: req.body }, { new: true });
listo

2019-04-19 23:36 UTC, dav793 approved these changes
Listo el PR!

2019-04-19 23:36 UTC, dav793 commented on src/controllers/user.controller.ts
> +        if (user != null) {
Excelente que le agregue manejo de errores! :raised_hands:

2019-04-19 23:36 UTC, merged